name: Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Install package dependencies
        run: pnpm install
        working-directory: web

      - name: Run build
        run: pnpm build
        working-directory: web
        env:
          CI: false

      - name: Bump manifest version
        run: node .github/actions/bump-manifest-version.js
        # The script now writes NEW_VERSION to GITHUB_ENV

      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: bump manifest version to ${{ env.NEW_VERSION }}'

      - name: Update branch
        working-directory: ./
        run: git push origin HEAD:main

      - name: Bundle files
        run: |
          mkdir -p ./temp/dirk_stores
          mkdir -p ./temp/dirk_stores/web/
          cp ./fxmanifest.lua ./README.md ./temp/dirk_stores
          cp -r ./locales ./temp/dirk_stores
          cp -r ./settings ./temp/dirk_stores
          cp -r ./src ./temp/dirk_stores
          cp -r ./web/build ./temp/dirk_stores/web/
          cd ./temp && zip -r ../dirk_stores.zip ./dirk_stores

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        id: auto_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Release ${{ env.NEW_VERSION }}"
          prerelease: false
          files: dirk_stores.zip
          automatic_release_tag: 'latest_production'
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}